//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NGUOIDUNG
    {
        public int MANGUOIDUNG { get; set; }
        public string TENNGUOIDUNG { get; set; }
        public string MATKHAU { get; set; }
        public string HOVATEN { get; set; }
        public string EMAIL { get; set; }
        public string SODIENTHOAI { get; set; }
        public byte[] HINHANH { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string TAOBOI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string CAPNHATBOI { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
    }
}
